name: staging(create tag - for acceptance test)
run-name: ${{github.event.head_commit.message}}(${{github.event.head_commit.ref}})

on:
    workflow_dispatch:
    push:
        branches:
            - staging

permissions: write-all

jobs:
    release:
        name: checkout
        if: github.repository == 'DEEPX-AI/dx_app'
        runs-on: 
          - self-hosted
          - sdk
        timeout-minutes: 20
        steps:
            - name: Clean
              run: |
                  sudo rm -rf ${{ github.workspace }}
                  mkdir -p ${{ github.workspace }}
            
            - name: Checkout 
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true
                token: ${{ secrets.GC_DCI_TOKEN }}
            
            - name: Create tag
              uses: rickstaa/action-create-tag@v1
              with:
                  tag_exists_error: false
                  tag: ${{ github.event.head_commit.message }}
                  force_push_tag: true
                  commit_sha: ${{ github.event.head_commit.ref}}
                  message: '${{ github.event.head_commit.message }}'
